### ISSUE TITLE
restructure CI workflows

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#150]
With the new pypi workflows (#148) we could maybe restructure the workflows a bit.
The pip workflows are much faster to run. So I would suggest we move the ``pylint``, ``isort``, and ``prospector`` things to that workflow and only run the slower conda ones if those pass?

**Comment by florian-huber** [comment]
I looked up GitHub Actions a bit more and it seems that it is possible to rely on other workflows, but it is really not intended to be used that way (rather recommended to stick to ``jobs`` relying on others).
So, we could fuse the pypi and the Anaconda workflows and stack them a bit more cleverly to keep testing times down (often pushes fail because of pylint, isort or such).

```
name: Build

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:

  fast_basic_test:
    name: Basic checks on code linting
    
  analyze_pypi:
    name: analyze (pypi) / python-${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: fast_basic_test
    ...

  analyze_anaconda:
    name: analyze (Anaconda) / python-${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: analyze_pypi
...
```
