### ISSUE TITLE
Store all filters in yaml file instead of predefined_processing_queries

### ISSUE THREAD

**Issue by niekdejonge** [matchms/matchms#478]
Currently in #455 the yaml files created will look something like:
``` yaml
# Matchms pipeline config file 
# Change and adapt fields where necessary 
# ==================== 
importing:
  queries: ../tests/testdata/pesticides.mgf
  references: ../tests/testdata/pesticides.mgf
predefined_processing_queries: minimal
predefined_processing_references: minimal
additional_processing_queries:
- - add_parent_mass
- - normalize_intensities
additional_processing_references: []
score_computations: []
logging:
  logging_file: ./local_data/my_pipeline.log
  logging_level: WARNING
```

Instead it would be better to store every individual filter step instead of the predefined processing_queries. This would look like:

``` yaml
# Matchms pipeline config file 
# Change and adapt fields where necessary 
# ==================== 
importing:
  queries: ../tests/testdata/pesticides.mgf
  references: ../tests/testdata/pesticides.mgf
filters_queries:
-- make_charge_int
-- interpret_pepmass
-- derive_ionmode
-- correct_charge
- - add_parent_mass
- - normalize_intensities
score_computations: []
logging:
  logging_file: ./local_data/my_pipeline.log
  logging_level: WARNING
```

This ensures that a yaml file always does the same analysis even if we later change the filters in "minimal". It also gives a clearer overview of what filters are used and in which order they are run.
